# Fastfile
default_platform(:ios)

platform :ios do
  desc "Build and upload the VoiceMemos app to TestFlight"
  lane :beta do
    match(type: "appstore")
    build_app(
      scheme: "VoiceMemos", # Replace with your scheme name if different
      export_method: "app-store"
    )
    

    api_key = app_store_connect_api_key(
      key_id: "6XM55L2239",   
      issuer_id: "69a6de7d-b15e-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey.p8", # Path to your Auth Key,
      duration: 1200,
      in_house: false
    )   

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: false # Set to false if you want to wait for the build processing to complete
    )

    clean_build_artifacts
  end
  
  lane :firebase do
    match(type: "appstore")
    match(type: "adhoc")
    gym(
        export_method: "ad-hoc",
        export_options: {
          provisioningProfiles: {
            "com.almaz5200.kidVoice": "match AdHoc com.almaz5200.kidVoice"
          },
          iCloudContainerEnvironment: "Production"
        }
    )

    firebase_app_distribution(
        testers_file: "testers.txt",
        release_notes: "APP"
    )
  end

  lane :update_certificates do
    firebase_app_distribution_get_udids(
        app: "1:1065583461322:ios:16133bf77b8f07977e4533",
        output_file: "udids.txt"
    )
    register_devices(devices_file: "./udids.txt")
    match(
        type: "development", 
        readonly: false,
        force_for_new_devices: true
    )
    match(
        type: "appstore", 
        readonly: false,
        force_for_new_devices: true   
    )
    match(
        type: "adhoc", 
        readonly: false,
        force_for_new_devices: true
    )
  end

end
